sonar.projectKey=DonovanDanielRomero-9_-sonar-practica
sonar.organization=donovandanielromero-9
sonar.projectName=Practica SonarCloud
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.java.source=11
sonar.host.url=https://sonarcloud.io
sonar.token=0628cd3980eebbcac453608d27dd76a7c31a05a5